### ISSUE TITLE
Sponsors Section

### ISSUE THREAD

**Issue by Moddynow69** [technobyte-nitkkr/frontier#22]
Sponsors (specific to Technobyte)

**Comment by Debatreya** [comment]
Please Assign 🙏 this to me

**Comment by Debatreya** [comment]
@Moddynow69 Sponsors mein kya krna hain excactly?

**Comment by Moddynow69** [comment]
@Debatreya You just need to filter(or create a local json) out the sponsors specific too technobyte , You can contact Anupma for the list.

**Comment by Debatreya** [comment]
Coding ninjas
Unstop
AECC global
Insightstone
TWC waffle kkr (Naam ka dekh lena)
Indigg
Aslaa esports

![image](https://github.com/technobyte-nitkkr/frontier/assets/116421305/7e2cec72-495b-4fe4-bc5e-22427bcfa4fe)
![image](https://github.com/technobyte-nitkkr/frontier/assets/116421305/170acd57-9e9c-4ee7-a9f0-36e253e0c402)


Inme se konse website pe ayenge?

**Comment by Debatreya** [comment]
![image](https://github.com/technobyte-nitkkr/frontier/assets/116421305/6cc98280-e91b-4e3d-a78a-e72428bd9a2b)


Need backend access, to add new sponsors
